### ISSUE TITLE
Broken link to cdk.dev slack on cdkday website 

### ISSUE THREAD

**Issue by SathyaBhat** [cdkday/website#4]
> If you want to chat to real CDK users, then join the cdk.dev slack space. 

This invite link is broken 

> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

**Comment by pgollucci** [comment]
The link works for me as of now

**Comment by skorfmann** [comment]
Ah, this is the cdkday website. Yes, that's an expired link, I'll submit a PR
